### ISSUE TITLE
Support configuration via a JS file (in addition to JSON)

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1065]
`tslint.js`, `tslintConfig.js`, could be called whatever as it would be passed to the `--config` option.

This allows more dynamic configuration of TSLint.

**Comment by atsu85** [comment]
There are couple of more benefits when using JavaScript files: 
1) it isn't so strict about commas after last element in array or property in object.
2) it allows commenting configuration.

**Comment by atsu85** [comment]
Based on the [documentation](https://github.com/palantir/tslint/#cli-1)
> If no option is specified, the config file named tslint.json is used, so long as it exists in the path.

I'd suggest that tslint.js would treated the same way. If both json and js files are present, js file could take precedence or error could be thrown (I wouldn't vote for using json file instead of js if both are present, as js conf would be newer feature and if the file is added, it probably means it should be used).

**Comment by JKillian** [comment]
This should work now given recent changes that use `require` to load non-JSON configuration files

**Comment by gunar** [comment]
@JKillian 	sorry, how would this work? Would it allow me to have dynamic rules that are enabled/disabled depending on the file being checked? Couldn't find more documentation on this.

**Comment by adidahiya** [comment]
@gunar no, you can't quite do that (see #3447), but you can have the configuration file be a `.js` file which sets exports with the `module.exports` object.

**Comment by gunar** [comment]
Thank you @adidahiya, to the solution seems to be to wait for tslint and eslint to merge as eslint already has per-file rules. Thank you.
