### ISSUE TITLE
Member-ordering issue with constuctors

### ISSUE THREAD

**Issue by alan-agius4** [palantir/tslint#1205]
### Bug Report

- __TSLint version__: `3.9.0`
- __TypeScript version__: `1.8.9`
- __Running TSLint via__: Gulp

#### TypeScript code being linted

```ts
export class SkeletonDirective {
	/*@ngInject*/
	constructor(
	) {
		// todo: constructor injection and dependency initialization here
	}

	static factory(): IDirectiveFactory {
		/*@ngInject*/
		const directive = (
		) => {
			return new SkeletonDirective();
		};
		return directive;
	}
};
```

with `tslint.json`:

```json
		"member-ordering": [
			true,
			"public-before-private",
			"static-before-instance",
			"variables-before-functions"
		],
```

#### Actual behavior

Declaration of public static member function not allowed to appear after declaration of public instance member function

#### Expected behavior

No warning as it is a constuctor

**Comment by lowkay** [comment]
I just commented on the bug fix that caused this to show up #1158 - it has broken some of our code too. The fix is reasonable though, it just doesn't separate field members from function members - treats everything as a "member".

I think there needs to be an additional option like "constructors-before-functions", certainly the following ordering is popular and should be supported:
fields,
constructors,
functions

where public/private and instance/static ordering is maintained in those sections.

**Comment by alan-agius4** [comment]
Unless they don't want to do something like: 

`        if (this.hasOption(OPTION_STATIC_BEFORE_INSTANCE) && previousMember.isInstance && !currentMember.isConstructor) {
            return Number(previousMember.isInstance) < Number(currentMember.isInstance);
        }`

**Comment by JKillian** [comment]
There's been other issues reported with this rule recently as well (see https://github.com/palantir/tslint/issues/1186). Definitely with all of you and want to fix this rule to make it more useful overall.

**Comment by JKillian** [comment]
Here's what I'm thinking as an appropriate resolution to this issue and to others: https://github.com/palantir/tslint/issues/1208 
Let me know what you all think!

**Comment by alan-agius4** [comment]
Looks good to me as you have more control on the ordering!
