### ISSUE TITLE
Generate CHANGELOG from commit messages

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#2032]
It gets cumbersome to compile the changelog for releases manually. We can enforce edits to CHANGELOG.md with a Github status check.

**Comment by JKillian** [comment]
This'll cause merge conflicts on every PR evertime another PR is merged. (You can fix this locally by messing with gitattributes, but it won't fix things on GH.) I recommend generating the changelog from commit messages instead - check out how a project like yarn does it.

**Comment by adidahiya** [comment]
@JKillian fair, but then we'll need to enforce a consistent style for squashed PR commit messages with a git hook. I'm on board; updating the issue title.

**Comment by JKillian** [comment]
Yep, enforcing consistent commit message style is a good idea! +1 from me

**Comment by JKillian** [comment]
Sorry, yarn wasn't necessarily the best example, a project like [angular2](https://github.com/angular/angular/commits/master) is a good example. I believe it uses [conventional-changelog](https://github.com/conventional-changelog/standard-version).

**Comment by ajafff** [comment]
You still need to extract a list of notable changes, since most users of tslint are not so interested in most internal work like rewrites for maintainability or performance.

For example [node](https://github.com/nodejs/node) does that. For the changelog they use [changelog-maker](https://github.com/rvagg/changelog-maker)

**Comment by nchen63** [comment]
fixed by #2196
