### ISSUE TITLE
[question] What is the type checker?

### ISSUE THREAD

**Issue by SteveALee** [palantir/tslint#2168]
The docs tell me how to turn the type checker on and that it requires some sort of program object but what is it for and what does it do?

Surely TS itself does all the type checking we could want?

My best guess is it's an expensive option that is off by default and needs to be turned on for some rules?

I discovered this as Microsoft/tslint-microsoft-contrib#330 fails

The problem there is TSLint throws an exception which breaks use in tools like the VS Code extension

**Comment by ajafff** [comment]
Taken from https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview
>Program: A collection of SourceFiles and a set of compilation options that represent a compilation unit. The program is the main entry point to the type system and code generation.

>Type resolver/ Checker: Resolving types of each construct, checking semantic operations and generate diagnostics as appropriate.

---------------

Some tslint rules need type information for expressions at a certain position to do their thing (like `no-for-in-array`, which needs to know if you are iterating over an array)
That information comes from typescript's `type checker`, which needs a `program`. A `program` consists of all required sources in the project. That is needed to get all type declarations and do useful control flow analysis and type inference.

You can run `tslint --program --type-check` to use the type checker. But gathering all files needed for the `program` is very expensive, so it is disabled by default.

`vscode-tslint` feeds the currently opened source file into `tslint`. That is done to lint your unsaved changes. Doing that with `--program --type-check` seems to be a lot more difficult (maybe impossible?). Those options are not enabled for that reason. That's why you get errors.

IMO running tslint with type checking is better done via cli.

**Comment by SteveALee** [comment]
@ajafff Thank you! My mistake was reading the ```TSLint``` docs. :)

'''vscode-tslint' use the library and that needs the project passed as you say. I created Microsoft/vscode-tslint#161. 

I can obviously switch from vscode to CLI to lint full project but then you lose the nice little red squiggles when you are editing which really enhance workflow.

An additional problem is TSLint throws using extends to turn off the rules is broken. You need to edit the base rules set. I raised an issue for that too.
