### ISSUE TITLE
Clash with zsh: zsh: permission denied

### ISSUE THREAD

**Issue by QuantumInformation** [palantir/tslint#2398]
I'm getting an error like so when running tslint:

tslint -c tslint.js  `client/Game.ts`
zsh: permission denied: client/Game.ts
Usage: tslint [options] file ...

see also https://github.com/robbyrussell/oh-my-zsh/issues/5133#issuecomment-289063736

**Comment by ajafff** [comment]
Remove the backticks. Otherwise your shell tries to execute `client/Game.ts`

Am 24.03.2017 17:01 schrieb "Nikos" <notifications@github.com>:

I'm getting an error like so when running tslint:

tslint -c tslint.js client/Game.ts
zsh: permission denied: client/Game.ts
Usage: tslint [options] file ...

see also robbyrussell/oh-my-zsh#5133 (comment)
<https://github.com/robbyrussell/oh-my-zsh/issues/5133#issuecomment-289063736>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/palantir/tslint/issues/2398>, or mute the thread

**Comment by adidahiya** [comment]
@ajafff is right. try `tslint -c tslint.js 'client/Game.ts'`. also why is your config file a .js file? check out the README.

**Comment by QuantumInformation** [comment]
Thanks, in the end I didn't need a tslint.json. I just run eslint with the tslint-eslint-rules parser.

https://github.com/QuantumInformation/Density-Wars/blob/master/.eslintrc.js#L2

Next thing I need to figure out is why I'm not getting any linting errors highlighting in webstorm with ts files, like with js files.
