### ISSUE TITLE
What JSON schema is being used for rule options metadata?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2419]
Related to my confusion in #2415. It looks related to http://json-schema.org/, but with some changes (`anyOf`?)?

**Comment by JKillian** [comment]
@JoshuaKGoldberg I believe it is json schema, as described [here](https://spacetelescope.github.io/understanding-json-schema/reference/combining.html). I'm not exactly sure what's happened in all the different drafts/specs/etc so can't promise exactly what version of json schema is being used haha.

The original intention for it was so that tslint.json configurations could be easily validated, just never got around to implementing that yet 😞

**Comment by JKillian** [comment]
Based on [this page], it seems that `anyOf` was introduced in Draft 04 of the json schema spec

**Comment by JoshuaKGoldberg** [comment]
Roger. Filed #2428 as a followup, thanks!
