### ISSUE TITLE
A path in an 'extends' option must be relative or rooted, but 'tslint-config-standard' is not. 

### ISSUE THREAD

**Issue by Paschalis89** [palantir/tslint#2548]
### Bug Report

- __TSLint version__: 4.0.0
- __TypeScript version__: 2.2.1
- __Running TSLint via__: Atom 

#### TypeScript code being linted

with `tslint.json` configuration:

```json
{
  "rules": {
    "no-duplicate-variable": true,
    "no-unused-variable": [
      true
    ]
  },
  "rulesDirectory": [
    "node_modules/tslint-eslint-rules/dist/rules"
  ]
}

```

#### Actual behavior

[15:53:45]  typescript error 
A path in an 'extends' option must be relative or rooted, but 'tslint-config-standard' is not. 

[15:53:45]  build dev failed: Cannot read property 'replace' of null 

#### Expected behavior

build done

Actually the problem is in my tsconfig.json

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  },
  "extends": "tslint-config-standard"

}

```

someone can help me?

**Comment by ajafff** [comment]
Put the "extends" in your tslint.json instead of tsconfig.json

Am 11.04.2017 16:03 schrieb "Paschalis89" <notifications@github.com>:

Bug Report

   - *TSLint version*: 4.0.0
   - *TypeScript version*: 2.2.1
   - *Running TSLint via*: Atom

TypeScript code being linted

with tslint.json configuration:

{
  "rules": {
    "no-duplicate-variable": true,
    "no-unused-variable": [
      true
    ]
  },
  "rulesDirectory": [
    "node_modules/tslint-eslint-rules/dist/rules"
  ]
}

Actual behavior

[15:53:45] typescript error
A path in an 'extends' option must be relative or rooted, but
'tslint-config-standard' is not.

[15:53:45] build dev failed: Cannot read property 'replace' of null
Expected behavior

build done

Actually the problem is in my tsconfig.json

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  },
  "extends": "tslint-config-standard"

}

someone can help me?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/palantir/tslint/issues/2548>, or mute the thread

**Comment by Paschalis89** [comment]
i already try, to put the exends in tslint instead, but now there isn't problem with build but, when my Ionic 2 app starts there are many errors with transpile i think because the errors now are about angular 2  like: 

Can't resolve all parameters for Storage: (?).

**Comment by ajafff** [comment]
> Can't resolve all parameters for Storage: (?).

That's caused by circular imports and is definitely not related to tslint.

Am 11.04.2017 16:32 schrieb "Paschalis89" <notifications@github.com>:
