### ISSUE TITLE
Debug tslint error

### ISSUE THREAD

**Issue by mxl** [palantir/tslint#2704]
### Bug Report

- __TSLint version__: 5.2.0
- __TypeScript version__: 2.3.2

Currently if an error is thrown while applying tslint rule it's [logged as warning](https://github.com/palantir/tslint/blob/master/src/linter.ts#L203) and only error message is included in log. This complicates debugging such cases. For example see #2696 where tslint printing the following log line:
> Warning: Cannot read property 'kind' of undefined

without any details like stacktrace.

I suggest to add `debug` or `verbose` option that will enable output of stacktrace.
If that's ok I can submit a PR.

I'm not alone http://stackoverflow.com/q/43577136/746347

**Comment by ajafff** [comment]
`TypedRule` used to throw an exception when tslint was not run with `--project --type-check`. That caused some trouble when using the same tslint.json in CLI and for example in `vscode-tslint`.
To fix this everything was wrapped in try-catch.

Reverting/changing that behavior was also on my agenda, because I think it causes more trouble than it's actually worth.

There are several options:
* Remove the try-catch, replace the `throw` in `TypedRule#apply` with `showWarningOnce('...'); return [];`
  * still outputs a warning when not type checking
  * bugs in rules will crash the process 
    * you notice that something when wrong
    * you get the whole stack trace
    * otherwise editor plugins might just swallow the warning
    * easier debugging by pausing at the uncaught exception
* log the whole stack trace by default
* add an option `--debug` or `--verbose` as described above and ...
  * throw
  * log the whole stack trace

Thoughts? @nchen63 @adidahiya @andy-hanson

**Comment by andy-hanson** [comment]
:+1: for printing the whole stack trace. It's pretty cryptic otherwise, since there's no indication that the message is being printed because of an exception.

**Comment by ajafff** [comment]
@andy-hanson printing the stack trace by default doesn't play well will the exception thrown in `TypedRule`. Instead of throwing there, it should just call `showWarningOnce` and return.
