### ISSUE TITLE
Only the last --exclude is honoured in 5.4.1

### ISSUE THREAD

**Issue by sandersn** [palantir/tslint#2855]
### Bug Report
#2853 doesn't fix the --exclude issue for 
- __TSLint version__: 5.4.1
- __TypeScript version__: master
- __Running TSLint via__: CLI

#### TypeScript code being linted

Typescript. Here's how to repro:

```sh
$ git clone https://github.com/Microsoft/TypeScript.git lint-failure
$ cd lint-failure
$ npm install
$ gulp lint
```

Which runs the command line: `node node_modules/tslint/bin/tslint Gulpfile.ts 'scripts/tslint/*.ts' 'src/**/*.ts' --exclude src/lib/es5.d.ts --exclude 'src/lib/*.generated.d.ts' --format stylish`

Removing the second `--exclude src/lib/*.generated.d.ts` correctly excludes src/lib/es5.d.ts, but not any of the generated d.ts files. So I think the error is that multiple excludes are ignored.

#### Actual behavior
Thousands of errors from src/lib/es5.d.ts because it is not excluded.

#### Expected behavior
No errors from src/lib/es5.d.ts

**Comment by adidahiya** [comment]
looking into this now

**Comment by sandersn** [comment]
Note that it seems to work on node 8. Maybe this is a change in command line parsing libraries of node?

**Comment by jmquigley** [comment]
It seems that using multiple "--exclude" options on one CLI are not working (at least not for me). I have a module build that is failing. I think that it is only respecting the last one from the CLI. According to the options one should be allowed to do this: "This option can be supplied multiple times if you need multiple globs to indicate which files to exclude." (tslint --help)

The CLI for sandersn shows multiple exclude options, where the original CLI above is using only one (which is why I believe 5.4.1 fixed it for you, but not for this other use case).

**Comment by adidahiya** [comment]
We did switch to commander in 5.4, that's probably also related... https://github.com/palantir/tslint/pull/2689

**Comment by sandersn** [comment]
I just upgraded to node 8 and still repro the issue locally. So our build system may not even be running tslint correctly on node 8.
