### ISSUE TITLE
no-angle-bracket-type-assertion --fix puts multiple casts in wrong order

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [palantir/tslint#2957]
### Bug Report

- __TSLint version__: 5.4.0
- __TypeScript version__: 2.4 RC
- __Running TSLint via__: (pick one) CLI

#### TypeScript code being linted

```typescript
<number><any>value
```

with `tslint.json` configuration:

```json
{
    "rules": {
        "no-angle-bracket-type-assertion": true
    }
}
```

#### Actual behavior

```typescript
value as number as any
```

#### Expected behavior

```typescript
value as any as number
```

**Comment by ajafff** [comment]
Some random thoughts:
The AST is a bit weird when dealing with type assertions. That may be the problem.

Or it's related to the sorting of the fixes, because both start at the same position and tslint usually sorts them by end position in descending order. Which will result in unexpected results when the length of the replacements differs.

**Comment by JoshuaKGoldberg** [comment]
Ehh, this particular sample is part of the test cases and I can't reproduce it. I'll close as related to #2955.

**Comment by JoshuaKGoldberg** [comment]
Got it. It is in fact sorting of the fixes.

**Comment by JoshuaKGoldberg** [comment]
Got it. It is in fact sorting of the fixes.

**Comment by shaunc** [comment]
Possibly related, --fix sometimes (in more complex code) "corrects" generic parameters: `Foo<Bar>` => `Foo as Bar`. It doesn't do this all the time though, and haven't figured out a good (simple) test file for a bug report yet....
