### ISSUE TITLE
Rule file-header should have an option to allow // comments

### ISSUE THREAD

**Issue by dileepkeeppalli** [palantir/tslint#3180]
Rule file-header is not working. Even if particular header in a file like  Copyright \\d{4} didn't add in the file or any wrong text adds, No Lint errors are getting.

- __TSLint version__: ~5.3.2
- __TypeScript version__: ~2.3.3
- __Running TSLint via__: angular CLI 

#### TypeScript code being linted

```ts
"file-header": [
    true,
    "Copyright \\d{4}"
  ]
```

with `tslint.json` configuration: tried in 2 different ways

``` json
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
   // lint
  },
  "file-header": [
    true,
    "Copyright \\d{4}"
  ]
}

```

```json
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
   // lint,
   "file-header": [
    true,
    "Copyright \\d{4}"
  ]
  },
  
}

```

#### Actual behavior
TS lint is not validating wheather the header text is present or not present
#### Expected behavior
TSLint is failing to validate the file header text

**Comment by IllusionMH** [comment]
@dileepkeeppalli is there a chance that you have BOM in your files?

**Comment by atifsyedali** [comment]
This is now broken for me too. It used to work.

I think this is due to https://github.com/palantir/tslint/pull/2525 which used to check if the given text was present in the entire file text range, but now only checks the first comment in the file. However, the header in the file may look like this...

```
// **********************************
// Copyright 2017 Company
// **********************************
```

And the first comment it brings up is `// **********************************` which does not match the regular expression that expects a multiline header.

However, this works though, because a multi-line comment is just one comment:

```
/***********************************
 * Copyright 2017 Company
 ***********************************/
```

**Comment by JoshuaKGoldberg** [comment]
Sounds like the rule could be given an option to consider consecutive `//` comments as one long file header.
