### ISSUE TITLE
Docs page for no-unused-new can be removed

### ISSUE THREAD

**Issue by BehindTheMath** [palantir/tslint#3185]
### Bug Report
The `no-unused-new` rule was removed in #2269. However, the page in the [docs](https://palantir.github.io/tslint/rules/no-unused-new/) still exists. It's not linked to anywhere, but the page itself could be removed as well.

**Comment by adidahiya** [comment]
ah, good point, thanks for the heads up.

**Comment by trivikr** [comment]
This happens because the buildDocs script just creates new files, it doesn't delete the files for old rules.
https://github.com/palantir/tslint/blob/404c06a0fbdeeacfb527523f965de430530a8fc1/scripts/buildDocs.ts#L138-L145

The rules was removed from code in #2269, and from the [core rules](https://palantir.github.io/tslint/rules/) documentation page. However, the [specific page](https://palantir.github.io/tslint/rules/no-unused-new/) for the rule was not removed.

**Comment by trivikr** [comment]
As per the comment from @ajafff https://github.com/palantir/tslint/pull/3230#pullrequestreview-63219790, this issue is not completely fixed as bringing up generated docs from **master** to **gh-pages** is a manual step.
