### ISSUE TITLE
Error: Debug Failure. at tryReuseStructureFromOldProgram

### ISSUE THREAD

**Issue by donaldpipowitch** [palantir/tslint#3188]
### Bug Report

- __TSLint version__: 5.7.0
- __TypeScript version__: 2.5.2
- __Running TSLint via__: Node.js API

#### TypeScript code being linted

https://github.com/donaldpipowitch/tslint-issue-3188

#### Actual behavior

It looks like an error is thrown, if more than two files are fixed at once.

```
first file logged
second file logged
Error: Debug Failure.
    at tryReuseStructureFromOldProgram (/Users/foo/node_modules/typescript/lib/typescript.js:69547:22)
    at Object.createProgram (/Users/foo/node_modules/typescript/lib/typescript.js:69310:34)
    at Linter.updateProgram (/Users/foo/node_modules/tslint/lib/linter.js:245:25)
    at /Users/foo/node_modules/tslint/lib/linter.js:235:13
    at Map.forEach (native)
```

I log the files in `Linter.prototype.applyFixes` before `_this.updateProgram(filePath);` is called.

If I run my linter again the output looks like this:

```
third file logged
fourth file logged
Error: Debug Failure.
    at tryReuseStructureFromOldProgram (/Users/foo/node_modules/typescript/lib/typescript.js:69547:22)
    at Object.createProgram (/Users/foo/node_modules/typescript/lib/typescript.js:69310:34)
    at Linter.updateProgram (/Users/foo/node_modules/tslint/lib/linter.js:245:25)
    at /Users/foo/node_modules/tslint/lib/linter.js:235:13
    at Map.forEach (native)
```

This goes on and on until no or just one file needs to be fixed.

#### Expected behavior

Fix everything in one run without errors.

**Comment by donaldpipowitch** [comment]
I added a small test case ✌️

**Comment by ajafff** [comment]
I think I found it:
You only create the `ts.Program` once (https://github.com/donaldpipowitch/tslint-issue-3188/blob/master/tslint.js#L13). TSLint needs to create a new program after each fix behind the scenes. TypeScript reuses parts of the original program to save some time creating the new one. That means AST nodes of SourceFiles are reused and modified to represent the new sources.
After creating the new program it's no longer safe to use the old one. That's why TypeScript throws an exception.

There are several possible fixes:
* check if `linter` applied any fixes and create a new program from scratch
* `program = linter.program` after `linter.lint()` - `program` is a private property of `Linter`, so you either need `(linter as any).program` or we need to make it public
* only create `linter` once

**Comment by donaldpipowitch** [comment]
> only create linter once

That's cool! Thank you for pointing this out. I'll make an update to the example in the docs. The old example called `new Linter` multiple times and I copied and pasted that into the new example.
