### ISSUE TITLE
Confusing warning messages for type checks

### ISSUE THREAD

**Issue by smasala** [palantir/tslint#3283]
See comment: https://github.com/palantir/tslint/pull/3282#issuecomment-334503570

FYI: @markuskeunecke

**Comment by ajafff** [comment]
For posterity:

>Then are both the documentation and the `warning` messages are confusing.
>
>If `typeCheck` and `project` are not defined but `completed-docs` in `tslint.json` is, then the `warning`:
>```
>Warning: The 'completed-docs' rule requires type information.
>```
>Is confusing, don't you think?
>
>However, rules defined in `tslint.json` that **do not** require `typeChecking` are evaluated regardless and the `tsconfig.json` in this instance is somehow found.
>
> When `typeCheck: true` is set then the output is the same as before. 
>
> Although `typeCheck` is no longer required (as you mentioned above), it is even more confusing that `project` must suddenly be set to evaluate `type requiring` rules.

**Comment by ajafff** [comment]
> However, rules defined in tslint.json that do not require typeChecking are evaluated regardless and the tsconfig.json in this instance is somehow found.

Why do you think that? If a rule does not need type information, it doesn't need the `tsconfig.json`. There's no need to find anything in this case.

> project must suddenly be set to evaluate type requiring rules.

That's not true. `--project` was always required for them to work. So was `--type-check` which is now obsolete.

---

Behind the scenes TSLint uses TypeScript's TypeChecker to get the type information. That TypeChecker needs the `tsconfig.json` to know which files belong to the project and which compiler options to use.

TSLint doesn't try to infer any configuration. That's why you are getting the above mentioned error.

I get your point that the error does not provide any help to resolve the problem.

On a related note: the documentation of each rule states if it needs type information or not. For example https://palantir.github.io/tslint/rules/match-default-export-name/ and the link on that page leads you to the docs describing how to provide type information https://palantir.github.io/tslint/usage/type-checking/
(This information is missing in the docs of `completed-docs`. I opened #3284 for that)

**Comment by markuskeunecke** [comment]
> I get your point that the error does not provide any help to resolve the problem.
And the documentation still points to the `type-check` flag. This hint should be removed from the documentation.

At least for us the requirement of `project` for type checking rules was not obvious. The clarification and discussion in #3282 lead us to the conclusion that documentation and message are not as clear as they could have been. And the other conclusion was that the proposed change is not the right way to fix the issue.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
