### ISSUE TITLE
Rewrite Development docs

### ISSUE THREAD

**Issue by ajafff** [palantir/tslint#3328]
https://palantir.github.io/tslint/develop/custom-rules/ could use some love:

- [ ] remove references to `RuleWalker` and `getOptions()`
- [ ] refactor examples to use the best practices described in performance tips
- [ ] how to build a package
  * with configuration presets
  * with custom rules
  * that works with node's module resolution for both `"extends"` and `"rulesDirectory"`

**Comment by aervin** [comment]
I'm still learning best practices myself but would be interested in contributing on this issue. It's my feeling that this portion of the docs could use some "dumbing down" via a comprehensive overhaul of its content and structure. One change I'd like to see is that the page's example be one of an _entire project_ rather than a single rule file.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for major new changes or features. See #4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
