### ISSUE TITLE
Add unicode-bom

### ISSUE THREAD

**Issue by jez9999** [palantir/tslint#3331]
ESLint has a `unicode-bom` rule. It should exist for tslint too.

**Comment by ajafff** [comment]
For posterity: https://eslint.org/docs/rules/unicode-bom is about requiring or disallowing the UTF-8 BOM (\uFEFF)

Since TSLint only works with unicode input, the rule can just be named `bom`.

**Comment by jez9999** [comment]
I've been investigating and it looks like each rule is passed a `SourceFile`:

    public apply(sourceFile: ts.SourceFile): Lint.RuleFailure[]

Unfortunately, `SourceFile`'s `.text` property has already had the BOM removed by the time it gets to the rule.  Can anyone suggest a way I can get at the actual raw file?  Does tslint need modifying to pass the raw file contents into the rule as well?

**Comment by ajafff** [comment]
@jez9999 the BOM is not removed by TSLint. There are already some rules that need to check if BOM is present:
https://github.com/palantir/tslint/blob/5bd6fc664dacc45d376e3ece0bcd97b5e1af2505/src/rules/alignRule.ts#L194

**Comment by jez9999** [comment]
Interesting, I have no idea how that works because when I compared `text` to the file data originally read via `fs`, the BOM had been removed.  Probably by `sys.readFile()`:

https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L95

**Comment by ajafff** [comment]
Yeah, you're right. I never noticed, because I only ever needed to ignore the BOM in rules.

You can still read the first 3 (I guess) bytes from the file to see if it has a BOM.

There is a way to avoid that if the `SourceFile` comes from TSLint and not from TypeScript's `Program`:

If `Rule#apply` is called, the SourceFile is created by TSLint and includes the BOM (if present). And you don't need to worry about encoding, because TSLint currently only supports UTF8.

If `Rule#applyWithProgram` is called, the SourceFile comes from TypeScript and may have the BOM stripped (depending on the CompilerHost). In that case you would need to do additional IO. You also need to handle UTF16 LE and BE, because they require a BOM. You can use `detectBufferEncoding` from `Lint.Utils` as a helper.

**Comment by jez9999** [comment]
Well the additional IO is pretty undesirable isn't it?  TypeScript really just needs to provide the raw data Buffer as part of the SourceFile.

**Comment by BooleT37** [comment]
The real issue with absence of thi rule is the fact that tslint fixer removes all BOMs from files. I have a very large project encoded specifically with utf-8 BOM, and couldn't use fixer for any rule because of it. The solution came down to manually editing source code of library in node_modules. I am sure I am not alone in this issue.

**Comment by saschanaz** [comment]
>The real issue with absence of this rule is the fact that tslint fixer removes all BOMs from files.

So #703 added the BOM removal behavior...

I would be happy to have a rule to keep BOM as:

* Microsoft requires UTF-8 BOM for every file in Windows Store apps
* Visual Studio inserts BOM by default to align with the store rule

TS files will not be in actual app package so removing BOM for them is okay, but still conflicts with the default VS behavior.

**Comment by JoshuaKGoldberg** [comment]
Note: per #4534, this issue will be closed in less than a month if no PR is sent to add the rule. If you _really_ need the rule, custom rules are always an option and can be maintained outside this repo!

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated** and no longer accepting pull requests for new rules. See #4534. 😱

If you'd like to see this rule implemented, you have two choices:
* **Recommended:** Use [typescript-eslint](https://typescript-eslint.io) to lint your TypeScript code with ESLint ✅
* **Legacy:** Write it as a [custom TSLint rule](https://palantir.github.io/tslint/develop/custom-rules/) 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
