### ISSUE TITLE
max-line-length: ignore long file paths

### ISSUE THREAD

**Issue by aervin** [palantir/tslint#3403]
A project's directory structure can become very "deep." `import` statements sometimes look like this:
```ts
import {
    StopListComponent
} from './some/maticulously/organized/project/billing-calendar/billing-calendar-route/stop-list/stop-list.component';
```
which `tslint` does not like
```
[tslint] src/app/app.module.ts[59, 1]: Exceeds maximum line length of n
```
This seems like it could be a common scenario. How about a config flag to ignore long file paths?

**Comment by ajafff** [comment]
IMO long paths are only a problem in imports. In all other places you can split the string into multiple parts and place each of them on a new line.

I think this will be covered by #1872

**Comment by DanielKucal** [comment]
Since #3099 has been merged, after new release you will be able to specify ignore pattern for max-line-length rule like `"^import "` and store each import statement in single line or keep it like it is now with ignore pattern set to i.e. `"^} from "`, eventually play with detecting slashes. I guess it can be closed now.

**Comment by keyvhinng** [comment]
Does someone know when the next release will happen ? Is there a release schedule ? I'll like to include this change on my project

**Comment by ajafff** [comment]
@keyvhinng all important bugfixes for the release are merged. You can expect a new version this week.
