### ISSUE TITLE
Is it possible to get access to tsconfig.json from a tslint rule

### ISSUE THREAD

**Issue by icasteleyn** [palantir/tslint#3617]
Hi,

In a customrule I would generate some javascript-code (fix-code when run in a javascript file).
I'm doing this through the typescript compiler itself. I have the option there to specify the version of javascript (ES5, ES6, ...).

I can off course make an option for this in the tslint.json for my customrule, however this is normally allready defined in the tsconfig.json itself ("target"-property).
I was wondering if I can get at the value of this property in the tsconfig.json file?

Thanks
Ike

**Comment by aervin** [comment]
Maybe `sourceFile.languageVersion` would be useful to you? It's a [ScriptTarget](http://ts2jsdoc.js.org/typescript/ts.html#.ScriptTarget) enum.

**Comment by aervin** [comment]
One way I've found is to use `applyWithProgram`: 
```ts
public applyWithProgram(sourceFile: ts.SourceFile, program: ts.Program): Lint.RuleFailure[] {
    const target = program.getCompilerOptions().target;  /* ts.ScriptTarget enum */
    return this.applyWithFunction(sourceFile, walk, ...);
}
```

**Comment by ajafff** [comment]
There are three ways to access the compilation target:
* in `Rule#applyWithProgram`: `program.getCompilerOptions().target` although this might be undefined so you need to use a default value
* `sourceFile.languageVersion` contains the correct target if TSLint is executed with `--project`, otherwise it's set to a default value by TSLint (currently ES5)
* try to read the file from disk
  * you may not find the correct tsconfig.json
  * you need to do all the parsing and extending stuff
  * `compilerOptions.target` may be undefined so you need to use a default value

**Comment by icasteleyn** [comment]
Thanks for the input. I can continue from here on.
It seems I would need to take some default value into account.

Thanks again.
