### ISSUE TITLE
v5.9.0 breaks build for bm-tslint-rules

### ISSUE THREAD

**Issue by karfau** [palantir/tslint#3700]
### Bug Report

- __TSLint version__: 5.9.0, 5.9.1
- __TypeScript version__: 2.6.1, 2.7.1 (I only checked with those two versions)
- __Running TSLint via__: CLI

#### tslint rule being **compiled**

https://github.com/bettermarks/bm-tslint-rules/blob/b550b5914d3ab4a405c95bddcac770fa8cde7c4e/src/noAbsoluteImportToOwnParentRule.ts

#### Actual behavior

running `npm run build` returns
```
> bm-tslint-rules@0.1.0 build /home/karfau/dev/bettermarks/bm-tslint-rules
> tsc -p .

node_modules/tslint/lib/runner.d.ts(60,27): error TS1209: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bm-tslint-rules@0.1.0 build: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bm-tslint-rules@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/karfau/.npm/_logs/2018-02-06T21_57_59_975Z-debug.log
```
[2018-02-06T21_57_59_975Z-debug.log](https://github.com/palantir/tslint/files/1700976/2018-02-06T21_57_59_975Z-debug.log)

#### Expected behavior
With `tslint` 5.8.0 the rule did compile just fine.

_I also found out that transpiiling rules to js files is no longer needed since one can use ts-node to run them, as is stated [here](https://palantir.github.io/tslint/develop/custom-rules/) (in the "final notes").
This worked for running the tests, but I have difficulties using the `ts` file as a rule in another projects.
I'm willing to create a minimal example for that problem, but I thin this is a rather different issue because it has a lot of implications on what dependees would need to do to be able to use the rule this way, so I think this should rather be sep. issue._

**Comment by alangpierce** [comment]
I'm running into this problem as well. In my case, I'm working on a tool (which happens to use `isolatedModules` in its config) that needs to parse TSLint output, so I pulled in the `IRuleFailureJson` type exported by tslint, which works great. However, importing that type causes the rest of tslint to be imported, so the `export declare const enum Status` line in runner.d.ts causes a type error.

Some more discussion about the issue here: https://github.com/Microsoft/TypeScript/issues/20703

My understanding is that it's generally bad practice to expose const enums in the public types for a package (partly because they can break some build configurations, and partly because inlining across projects can lead to subtle bugs after upgrading a dependency), so maybe it's best to just turn this into a regular enum?

**Comment by karfau** [comment]
@contributers I'm still not able upgrade my rule set even to newest version 5.11

Can somebody help me to understand how to either get around the problem or how to support a fix?

**Comment by karfau** [comment]
When removing the compiler option `isolatedModules` the uild output didn't change but the error stopped popping up.

**Comment by alangpierce** [comment]
This is still causing problems for me, since I want to be able to import TSLint types without having to disable `isolatedModules` in my project. I guess I'll file another issue or submit a PR.
