### ISSUE TITLE
multiple files produce invalid json output

### ISSUE THREAD

**Issue by saily** [palantir/tslint#379]
When i want to run `tslint --format=json --file=/a/b/c.ts --file=/b/c/d.ts --out=tslint-result.json` this will produce an invalid json file because it just concats the output from each file. This also happens if you output to stdout.

**Comment by EarthCitizen** [comment]
This is a huge problem for me as well. I need to send the results to Sonar, but the report is invalid.

**Comment by JKillian** [comment]
Agreed that this is quite flawed. @EarthCitizen if you're able to do a little text-processing of the results, if you replace `}{` with `},{` and surround the whole file with `[]`, it should be a valid JSON and usable. Obviously this is not ideal though...

**Comment by EarthCitizen** [comment]
Looking at the problem briefly, it does not *seem* like a difficult fix.

1) `class Linter` constructor needs to take a list of file names instead of just one
2) `class Linter.lint()` needs to iterate over those files and push all the failures to the common stack
3) `tslint-cli.ts` `processFile()` should be changed to `processFiles()` and take a list of file names instead of just one
4) `processFiles()` would be called just once, and do its validations on all the files

DISCLAIMER: of course I do not know the full ramifications of these changes, but it *seems* like it would work

**Comment by JKillian** [comment]
@EarthCitizen Seems like sensible changes.Changing `processFile` to `processFiles` seems fine, it's an internal method so no real harm done. Changing the `Linter` constructor is trickier, as it is a public API and changing it would probably break many tools that use/wrap TSLint. However, I think it might be possible to make it take either a single filename or an array of filenames and handle the two cases appropriately.

I _think_ with these changes the formatter API could stay the same, which is a very good thing.

I'm actually going to close this issue because I see that #656 is a broader description of this same problem. We can continue the discussion there though!

**Comment by EarthCitizen** [comment]
When I originally looked at this and commented in #379, I was not paying attention to the fact that the Linter constructor wants the file name AND the contents of the file. This makes refactoring class Linter a bit difficult. If there needs to be backwards compatibility with a public API, then perhaps mark that class deprecated and start over in a new class.

If that were to happen, the class should get the file contents itself when it is linting and not receive them in the constructor.
