### ISSUE TITLE
'expected variable-declaration to have a typedef' lint error on for loops

### ISSUE THREAD

**Issue by janez-svetin** [palantir/tslint#3912]
### Bug Report

- __TSLint version__: 5.10.0
- __TypeScript version__: 2.7.2
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
// code snippet (for-loop.ts file)
const split = [ 1, 2, 3, 4, 5 ];
for (let i = 0; i < split.length; i += 1) {
  console.log("Foo Bar!");
}
```

with `tslint.json` configuration:

```json
{
  "extends": [
    "tslint-eslint-rules"
  ],
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
    "typedef": [
      true,
      "variable-declaration"
    ]
  }
}

```

#### Actual behavior
```
ERROR: test-for-loop.ts[1, 7]: expected variable-declaration: 'split' to have a typedef
ERROR: test-for-loop.ts[2, 10]: expected variable-declaration: 'i' to have a typedef
```
#### Expected behavior
The typedef rule should ignore variables declared within for loop declarations.

Looking at the source, [typedefRule.ts](https://github.com/palantir/tslint/blob/master/src/rules/typedefRule.ts#L176) line 176, there is condition written:
```ts
if (parent.kind === ts.SyntaxKind.CatchClause
    || parent.parent.kind === ts.SyntaxKind.ForInStatement
    || parent.parent.kind === ts.SyntaxKind.ForOfStatement) {
  return;
}
```

I think it should also include basic `ForStatement` kind:
```ts
if (parent.kind === ts.SyntaxKind.CatchClause
    || parent.parent.kind === ts.SyntaxKind.ForInStatement
    || parent.parent.kind === ts.SyntaxKind.ForOfStatement
    || parent.parent.kind === ts.SyntaxKind.ForStatement) {
  return;
}
```
In this case it does not falesly reports on 'i' to have typedef.

Any specific reason it is left out?

**Comment by JKillian** [comment]
TypeScript actually doesn't allow a type annotation on the LHS of `for-in` or `for-of` loops, so the `typedef` rule must not check for one there. Since a regular `for` loop can contain an arbitrary initializer, it makes sense to check for a type declaration there.

I think the real issue here is that the `typedef` rule isn't great and often leads to overly-verbose code. See https://github.com/palantir/tslint/issues/711 for somewhat related discussion. What'd be best here may be to let `typedef` ignore simple declarations like `let i = 0` all together.
