### ISSUE TITLE
Require index for for arrays

### ISSUE THREAD

**Issue by NN---** [palantir/tslint#3971]
Today TSLint has the opposite rule.

```ts
const arr = [1,2];
for (const e in a) {} // TSLint has rule for this
for (const e of a) {} // TSLint has rule for this
```

Unfortunately in IE usage of 'for..of' is very slow and using regular for-index works much faster.
I would like to have a rule which prohibits for..in and for..of for arrays and requires the for-index pattern:

```ts
for (let i = 0, n = arr.length; i < n; ++i) {
 ...
}
```

**Comment by johnwiseheart** [comment]
I feel like generally the `for..in` and `for..of` are the preferred way of writing arrays. I don't think it makes sense to have contradicting rules in the main `tslint` repo, as it's intended to be an opinionated rule set rather than an extremely broad rule set. This is probably better written as a custom rule.
