### ISSUE TITLE
Object.assign not detecting mutation

### ISSUE THREAD

**Issue by alex-deas** [palantir/tslint#4146]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.1.0
- __Running TSLint via__: CLI & ALE

#### TypeScript code being linted

```ts
let x: object = {}
Object.assign(x, { x: 1})
```

with `tslint.json` configuration:

```json
{
        "prefer-const": true
}
```

#### Actual behavior
`Identifier 'x' is never reassigned; use 'const' instead of 'let'.`
#### Expected behavior
TSLint recognises that Object.assign is mutating the first argument

**Comment by giladgray** [comment]
@alex-deas this is actually the expected behavior. `assign` merges later objects into the first one but it doesn't actually update the _reference_ (what the variable points at). so `x` is `x` before and after assignment. the _contents_ of `x` have changed, but it's still the same _object_.

preventing object mutation requires a different approach, such as immutable data structures. i would encourage a typesafe approach to this where the compiler itself can ensure objects are never mutated. good examples are `readonly` properties and immutable data structures.

**Comment by alex-deas** [comment]
Fair enough, it's been a while since I've had to think about JS and that a `const` isn't a constant..

**Comment by giladgray** [comment]
Not exactly... A `const` is constant in that it cannot be reassigned. But js objects are mutable and can be modified without reassignment.
