### ISSUE TITLE
TypeError: builtins.indexOf is not a function

### ISSUE THREAD

**Issue by liquid36** [palantir/tslint#4285]
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 2.9.2
- __Running TSLint via__: CLI 

#### TypeScript code being linted

```ts
const pdfkit = require('pdfkit');
```

with `tslint.json` configuration:

```json
"no-implicit-dependencies": [
            true,
            "dev"
        ],
```

#### Actual behavior
```
The 'no-implicit-dependencies' rule threw an error in 'api/utils/pdfGenerator.ts':
TypeError: builtins.indexOf is not a function
    at walk (/api/node_modules/tslint/lib/rules/noImplicitDependenciesRule.js:72:26)
    at Rule.AbstractRule.applyWithFunction (/api/node_modules/tslint/lib/language/rule/abstractRule.js:39:9)
    at Rule.apply (/api/node_modules/tslint/lib/rules/noImplicitDependenciesRule.js:38:21)
    at Linter.applyRule (/api/node_modules/tslint/lib/linter.js:197:29)
    at /api/node_modules/tslint/lib/linter.js:139:85
    at Object.flatMap (/api/node_modules/tslint/lib/utils.js:151:29)
    at Linter.getAllFailures (/api/node_modules/tslint/lib/linter.js:139:32)
    at Linter.lint (/api/node_modules/tslint/lib/linter.js:99:33)
    at /api/node_modules/tslint/lib/runner.js:209:32
    at step (/api/node_modules/tslib/tslib.js:133:27)
```
On line 97, variable `builtins` is expect to be an array, however `builtins` is a function.

https://github.com/palantir/tslint/blob/1012e56fb2c0b5275e6a737181e62f586de991f1/src/rules/noImplicitDependenciesRule.ts#L97

I checked the code of `buildin-modules` and return this:

```javascript
function bufferFrom (value, encodingOrOffset, length) {
  if (typeof value === 'number') {
    throw new TypeError('"value" argument must not be a number')
  }

  if (isArrayBuffer(value)) {
    return fromArrayBuffer(value, encodingOrOffset, length)
  }

  if (typeof value === 'string') {
    return fromString(value, encodingOrOffset)
  }

  return isModern
    ? Buffer.from(value)
    : new Buffer(value)
}

module.exports = bufferFrom
```

**Comment by JoshuaKGoldberg** [comment]
👋 @liquid36 thanks for posting this! Your bug is odd because that's not the code under `builtin-modules` on any machine I've tried this on.

`index.js`:

```javascript
'use strict';

var blacklist = [
	'freelist',
	'sys'
];

module.exports = Object.keys(process.binding('natives')).filter(function (el) {
	return !/^_|^internal|\//.test(el) && blacklist.indexOf(el) === -1;
}).sort();
``` 

...which is roughly the same in the [`1.X`](https://unpkg.com/builtin-modules@1.0.0/index.js), [`2.X`](https://unpkg.com/builtin-modules@2.0.0/index.js), and [`3.X`](https://unpkg.com/builtin-modules@3.0.0/index.js) versions of the package. 

It looks like the code you posted is from the [`buffer-from`](https://github.com/LinusU/buffer-from/blob/master/index.js) package. Spooky. Looks like your npm installation was corrupted somehow. Try deleting your `node_modules` directory and re-running your package installation command (`npm i` or `yarn`). If that doesn't fix it, you'll want to look into the npmjs issue tracker: https://npm.community/.

Hope that helps!
