### ISSUE TITLE
Skip JSON file linting

### ISSUE THREAD

**Issue by aprilrd** [palantir/tslint#4426]
### Feature request

Because Typescript now allows importing json file directly, tslint rules apply to json files as well (see #4089). Typescript already catches invalid json errors (see https://github.com/Microsoft/TypeScript/issues/25452), so no json linting by tslint is necessary.

So let's have all rules skip json files.

**Comment by adidahiya** [comment]
I assume you are importing JSON files using [the TS 2.9+ `--resolveJsonModule` option](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#new---resolvejsonmodule), correct?

I think we can implement this change without calling it an API break, since the behavior of linting JSON files is almost certainly unintended and doesn't seem useful.

**Comment by adidahiya** [comment]
closing in favor of https://github.com/palantir/tslint/issues/3957
