### ISSUE TITLE
5.13 introduced a breaking change

### ISSUE THREAD

**Issue by alan-agius4** [palantir/tslint#4555]
### Bug Report

- __TSLint version__: 5.13
- __TypeScript version__: 3.2
- __Running TSLint via__: (pick one) API

This commit https://github.com/palantir/tslint/commit/9000479b69c1f4808acf1dee284b47fbbbfbef13 caused the API signature to changes and caused a breaking change in a minor release of tslint for API users.  

The issue is that now `format` method needs an additional parameter which is not optional, and hence it will be fail during compile time and during runtime since `fileNames` is not specified.

#### Expected behavior
Possible solutions;
1) Revert the change, release a patch & release this in a major
2) Make this optional

Relates to https://github.com/angular/angular-cli/issues/13783

**Comment by adidahiya** [comment]
Ah, sorry about that, I should have been more careful about `AbstractFormatter` and made sure its signature matched `IFormatter` exactly so that this break wouldn't happen (I was only focusing on `IFormatter` because that's the only one exported as public API)... maybe there's room for a lint rule here like https://github.com/palantir/tslint/issues/4175 to catch this in the future

**Comment by adidahiya** [comment]
I'll fix this and release 5.13.1

**Comment by alan-agius4** [comment]
Thank you
