### ISSUE TITLE
Support the abstract keyword

### ISSUE THREAD

**Issue by weswigham** [palantir/tslint#528]
At present, any appearance of the `abstract` keyword causes a missing semicolon lint error on that line.

**Comment by adidahiya** [comment]
Just to confirm, this is TS 1.6 syntax, right?

**Comment by weswigham** [comment]
Yes. It's in the master branch of TS (and used inside the compiler) already.

**Comment by adidahiya** [comment]
blocked on #474

**Comment by adidahiya** [comment]
Fixed on `v2.5.0-dev.1`. We should add regression tests though.

**Comment by MatejQ** [comment]
Hi,
found this issue via google. We are getting tslint warning "missing semicolon" on abstract keywords as well. We are using Visual Studio 2013, TypeScript is version 1.7, and tslint version is the one shipped with "web essentials" - should be newer than August 2015 when this issue was closed I guess...
We are also getting "expected an assignment or function call" warning on the abstract class.

On a method:
![method](https://cloud.githubusercontent.com/assets/14346231/16009361/a49ca3e4-317c-11e6-9c5f-6e3ac2b4a1fb.PNG)

On a class:
![class](https://cloud.githubusercontent.com/assets/14346231/16009373/b30f1222-317c-11e6-9d19-fdd3191dbf1f.PNG)

These are the warnings:
![error](https://cloud.githubusercontent.com/assets/14346231/16009441/040eecce-317d-11e6-8500-f9151dc58779.PNG)

What should we do?
