### ISSUE TITLE
Publish release with the "next" dist-tag

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#536]
Let's wait until #535 is resolved to do this.

This will resolve #474.

**Comment by adidahiya** [comment]
What version should we release this as? `v2.5.0-dev.1`?

Since we can't overload versions on npm (even with distinct dist-tags, since that's only a pointer), this would prevent us from releasing any minor version bumps from the `master` branch.

Another option would be to release on the `v3.x` line as `v3.0.0-dev.1`.

Thoughts @gscshoyru, @ashwinr?

**Comment by gscshoyru** [comment]
We should probably mirror what typescript is doing with their nightly -- tag as next, and put the date at the end -- so 2.6.0-dev.20150804 

There haven't been any breaking changes since 2.4.2 -- so I don't think we should jump to 3.x. 

I also kinda want to do 2.6 as opposed to 2.5 so our minor mirrors typescript's minor, but that's probably not necessary.

**Comment by adidahiya** [comment]
I think we'll be releasing on an ad-hoc basis, not nightly, so I don't think we should use the date syntax (it might be confusing).

And the 2.5 vs 2.6 argument isn't very convincing, so I'll stick with 2.5
