### ISSUE TITLE
Enforce ALL_CAPS variables to be declared as const

### ISSUE THREAD

**Issue by aicioara** [palantir/tslint#604]
ALL_CAPS variables, by convention are constants. It would be nice to have a rule that enforces `const` instead of `let` for those.

This might not be needed if https://github.com/palantir/tslint/issues/491 is active, but I prefer this weaker form.

**Comment by JoshuaKGoldberg** [comment]
I would argue that this complements `prefer-const` quite nicely. Together, they enforce that any variable in UPPER_CASE must be `const` and therefore never modified.

**Comment by reduckted** [comment]
Check out [tslint-consistent-codestyle](https://github.com/ajafff/tslint-consistent-codestyle) and the `naming-convention` rule. It's very flexible and you should be able to get the outcome that you're after. 

The only thing is that it sort of works in the opposite direction to what you wanted. Instead of enforcing `const` for uppercase variable names, it would enforce uppercase variable names for `const` variables.

**Comment by adidahiya** [comment]
fixed by #2936
