### ISSUE TITLE
Unable to build on Windows 7

### ISSUE THREAD

**Issue by littleninja** [palantir/tslint#615]
Running on a Windows 7 OS with NodeJS (0.10.33) and npm (2.14.0) following modules are global installed:
- grunt
- typescript
- tsd
- coffee-script

Ran `npm install` with only warnings. Ran `grunt` with errors on missing modules (dateformat, ...). I tried installing them one at a time globally (-g) and am stuck at this error:

```
Error: Cannot find module './lexer'
```

Is there something I'm missing for getting a workstation setup to develop on Windows? A Mac workstation with similar configuration has no issues.

**Comment by vmmitev** [comment]
Doesn't look like an OS problem. Neither is it related to TSLint's build configuration (as you said it works on your Mac).

By the looks of things you're probably missing one of the following local files:
`{tslint-root}\node_modules\grunt\node_modules\coffee-script\lib\coffee-script\lexer.js`
or
`{tslint-root}\node_modules\mocha\node_modules\jade\lib\lexer.js`

Most likely it's because of a problem that occurred during `npm install`. Try cleaning your local repo with `git clean -fdx` then clean the npm's cache with `npm cache clean` and run the install process again. You can run `git reset --hard` as well for good measure, just make sure you saved any local changes before trying any of this.

There's a chance the problem is in the global installation of grunt so try reinstalling it as well:
```bash
npm uninstall grunt-cli --global
npm install grunt-cli --global
```

As far as I know you don't need any other npm to be installed globally to run the build.

I hope this helps.
