### ISSUE TITLE
npm causes Error if I install tslint with typescript@1.8.0-dev-******

### ISSUE THREAD

**Issue by saneyuki** [palantir/tslint#810]
## env

my package.json is specified like this:

- `^tslint@3.0.0`
- `typescript@1.8.0-dev.*********` (my package.json locks tsc versions)

## step to reproduce

1. go to my project dir.
2. rm -rf nodo_modules/
3. npm install 

## result

- `npm WARN EPEERINVALID tslint@3.0.0 requires a peer of typescript@>=1.6.2 but none was installed.`
  - I suspect https://github.com/palantir/tslint/commit/9bd325aed280971f981ed85b6486312a0b30c20d is caused this....?

**Comment by JKillian** [comment]
@saneyuki The issue here is that the semver specification, `>=1.6.2` doesn't include dev releases of typescript, and thus npm isn't happy. This is just a warning though (I think) so you can probably ignore it.

Another fix is to use `tslint@next` or `tslint@3.0.0-dev.3`. Our dev release line is made to pair up with the dev releases of TypeScript, so it's probably the best bet for you. Let me know if this helps!

**Comment by saneyuki** [comment]
@JKillian

Thank you for your answer! At this time, `tslint@next` is still `tslint@3.0.0-dev.3` and there are some difference between `master` (stable?) and `next` branch by the commit log. Are their difference originated from the API difference of typescript compiler's development revisions?

**Comment by JKillian** [comment]
In general, dev releases should always be feature-equal or feature-ahead of the stable releases. Sometimes dev releases will have features that will only work with newer versions of TypeScript.

You're correct though - there are actually a small bugfix right now that's in the main 3.0.0 release but not in the latest dev release. That's just an anomaly because we haven't done a dev release since a few days ago, the next dev release will contain all those changes.

**Comment by saneyuki** [comment]
@JKillian 
aha, I understand tslint's release branch policy. 
I close this issue. Thank you for mentoring!
