### ISSUE TITLE
[Suggestion] Require that rules declare whether they enforce formatting or not

### ISSUE THREAD

**Issue by myitcv** [palantir/tslint#846]
We use `tsfmt` to format our code, hence any `tslint` rules that enforce a specific formatting of code are redundant... and indeed might even conflict with `tsfmt`. 

Suggestion would be to have rule authors declare whether a rule affects formatting or not, and then have the option of running `tslint` in a mode which does not execute any such formatting-directed rules (regardless of the rules listed in `tslint.json`)

A natural conclusion of this is that any rule that enforces formatting (and hence is declared as such) should not also enforce/require non-formatting conditions - but I think this natural split already exists amongst the current ruleset.

Another reason for wanting authors to declare a rule one way or t'other is that automatic documentation generation (#830) will be possible (e.g. annotate a rule as affecting formatting)

Thoughts?

**Comment by JKillian** [comment]
I feel that having an explicit option to run tslint in a way that excludes non-formatting rules is probably unneeded complexity, since users can just set up a tslint.json with the rules they wish.

From a rule metadata perspective though, it's a more intriguing idea to me. It seems reasonable to mark rules by their type: whether they find stylistic errors or find possible runtime errors. This is useful info to know about a rule for documentation generation like mentioned above or for other possible reasons.

I think a field like this would be fine once we have a better metadata system for rules and their options (https://github.com/palantir/tslint/issues/674). Ideas/proposals for #674 / #629 appreciated!

**Comment by JKillian** [comment]
I'm thinking there are really three types of rules:

* Rules that improve _readability_ (style rules)
* Rules that improve _maintainability_
* Rules that watch for _functionality_ bugs

For example (I just chose a few rules):
`comment-format`: _readability_
`no-string-literal`: _functionality_
`trailing-comma`: _maintainability_

The distinction between _maintainability_ and _readability_ is somewhat blurry, but essentially, _readability_ is about the way the code looks, whereas _maintainability_ is about the way the code can be edited. `trailing-comma` (and `object-literal-sort-keys` as another example) don't make the code look nicer, but they make the code easier to edit or improve git diffs.

Does this seem reasonable to you @myitcv? Think there should be other or different divisions?

**Comment by adidahiya** [comment]
[ESLint](http://eslint.org/docs/rules/) has these categories:

- Possible Errors
- Best Practices
- Variables
- Node / CommonJS
- Stylistic Issues
- ES6

**Comment by JKillian** [comment]
Not a big fan of the ESLint categories, they seem kind of overlapping. I think we could have better categories. Is Possible Errors vs. Best Practices a distinction we'd want to make? They both seem like subcategories of my proposed functionality category.

**Comment by JKillian** [comment]
I tried to sort the rules into the three categories I suggested here: http://palantir.github.io/tslint/rules/
but not entirely happy with its usefulness / distinction between the three.

**Comment by JoshuaKGoldberg** [comment]
Rules now do mention in their metadata a `type: "formatting"`, `type: "style"`, or similar. Anything more seems out of scope given #4534.
