### ISSUE TITLE
Option to ignore .d.ts files

### ISSUE THREAD

**Issue by louy** [palantir/tslint#847]
In my projects all .d.ts files are automatically generated and I don't want to lint them. This means that I can't just `tslint **.ts" because that'd include them as well. What I end up doing is 

``` bash
find -name *.ts . -echo0 | grep -i .d.ts | grep -i node_modules | xargs tslint
```

which is really annoying.

Related: #692 #680

**Comment by louy** [comment]
I can submit a PR for this if #827 gets merged.

**Comment by louy** [comment]
@adidahiya What do you think? I believe it should be opt-in.
Anyway it's as simple as pushing `"**/*.d.ts"` to `GLOB_IGNORE` in #857.

**Comment by giladgray** [comment]
I'd like a way to do this in config. For instance, Atom insists on linting the `.d.ts` files in my typings directory, which rarely conform to my tslint config because they come from the wider world. Also those files can be enormous (react.d.ts is 2200+ lines) so it's probably shave of some loading time if they weren't linted.

**Comment by ajafff** [comment]
#1006 added the ability to specify exclude patterns via CLI
When linting with `--project` *.d.ts files are excluded.
