### ISSUE TITLE
Supply files to lint in tsconfig.json

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#858]
Discussion moved from #692 

If provided the path to a `tsconfig.json` file, TSLint should:
- lint all the files listed in the `"files"` list and files they reference via imports or references
- ignore `.d.ts` files by default, but provide an option to lint those too

Q: should this be the default if no files are specified? i.e. TSLint searches for a `tsconfig.json` file in the same way it currently searches for a `tslint.json` file

**Comment by xogeny** [comment]
I'd like to point out that almost none of my `tsconfig.json` files actually have an entry for `files`.  Generally, they simply have an entry for `exclude`.  So you should consider that as well.  It would be idea if `tslint` linted all files that would be compiled for a given `tsconfig.json` file.

**Comment by JKillian** [comment]
@xogeny Agreed. It needs to follow the same conventions as `tsc`, either using the `files` field or the `exclude` field. It also will ignore any `.d.ts` files by default, as this seems like the behavior most people would want.

**Comment by adidahiya** [comment]
if there isn't one already, we should try to get an API endpoint in TS languages services to return the list of files in the compilation path. otherwise this task will be cumbersome & prone to break in future versions of tsconfig.json

**Comment by JKillian** [comment]
Lines [491](https://github.com/Microsoft/TypeScript/blob/51fd41b0c7b0f38335f8a2de6f5cd66b278c5a9c/src/compiler/commandLineParser.ts#L491) and [447](https://github.com/Microsoft/TypeScript/blob/51fd41b0c7b0f38335f8a2de6f5cd66b278c5a9c/src/compiler/commandLineParser.ts#L447) in `tsc.ts` look relevant. They're `exported` but also marked `@internal` at the top.

**Comment by JKillian** [comment]
Here's how [https://github.com/SitePen/dts-generator/blob/a7a2482f0d2927879fb18a9fc597ef7b276aa3a6/index.ts#L107](dts-generator) reads tsconfig files. Seems pretty easy

**Comment by adidahiya** [comment]
@JKillian nice, that looks promising. I imagine `configParseResult.fileNames` handles the `files` and `exclude` options for us

**Comment by dsebastien** [comment]
+1

**Comment by unional** [comment]
Would prefer to put it in tslint.json instead of `tsconfig.json`. There could be multiple `tsconfig.json` in different folders (e.g. isomorphic application or lib vs spec).
IDE tools such as vscode-tslint or atom-tslint should read one source to determine what files to include/exclude.
`tslint.json` would be a better choice.

**Comment by alexeagle** [comment]
I agree that `tslint.json` configures the `tslint` tool and should be told which files to ignore.
In my case, I want to ignore linting generated files. These are included in `.gitignore` but *need* to be present in TS for the program to compile.

On the other hand, I could see an include specifier in `tslint.json` that points to a `tsconfig.json` to delegate the decision of which files to lint. This is convenient for people who want to control the linter by adding/removing files from the program.

Note that some editors (looking at you, Atom) complain if `tsconfig.json` includes stuff it doesn't recognize, because it has its own schema validation instead of using `ts.parseJsonConfigFileContent`

Answering the question from above, the correct way to ask TypeScript for all the files it would transpile is `program.getSourceFiles()`. Just re-using the `tsconfig.json` parsing isn't enough, because files can be included in the program simply by being referenced from another file in the program (eg. you can `files: ['index.ts']` to find the whole program reachable through there)

**Comment by ajafff** [comment]
All features discussed above are already implemented:
* when `--project` is present, TSLint uses all files included in the project (excluding .d.ts)
* using `--project` together with a list of files only lints the files explicitly specified
* `--exclude` or `linterOptions.exclude` (in tslint.json) can be used to exclude certain files that are included in the project
* linting files that are not in the project does not work

**Comment by jgornick** [comment]
@ajafff What about using `--project` with the tsconfig specifying exclude? I would expect tslint to also exclude the files specified in the tsconfig exclude.

**Comment by ajafff** [comment]
@jgornick that's how it already works. If a file is excluded in tsconfig.json it is not part of the project and will therefore not be linted at all.

**Comment by apieceofbart** [comment]
@ajafff What about a reverse case: I have some file I exclude in `tsconfig` but I would like to include them for linting. I am not able to pass other filename to `tslint`. Is the only way to use CLI params?

**Comment by gf3** [comment]
@ajafff that's not the functionality i'm seeing on `5.9.1`. if tslint is passed a file that is excluded in tsconfig it throws an error and prevents linting completely:

<img width="1314" alt="screen shot 2018-02-26 at 11 41 52 am" src="https://user-images.githubusercontent.com/18397/36682838-21d70f4a-1aea-11e8-9d21-48a017c8f3e5.png">
